

articles_cols = {
            'Lens ID': 'lens_id', 
            'Title': 'title', 
            'Date Published': 'date_published', 
            'Publication Year': 'year_published',
            'Publication Type': 'publication_type', 
            'Source Title': 'source_title', 
            'ISSNs': 'issns', 
            'Publisher': 'publisher',
            'Source Country': 'source_country', 
            'Author/s': 'authors', 
            'Abstract': 'abstract', 
            'Volume': 'volume', 
            'Issue Number': None,
            'Start Page': 'start_page', 
            'End Page': 'end_page', 
            'Fields of Study': 'fields_of_study', 
            'Keywords': 'keywords', 
            'MeSH Terms': 'mesh_terms',
            'Chemicals': None, 
            'Funding': None, 
            'Source URLs': 'source_urls',
            'External URL': None,
            'PMID': 'pmid',
            'DOI': 'doi',
            'Microsoft Academic ID': 'magid',
            'PMCID': 'pmcid',
            'Citing Patents Count': None,
            'References': 'references',
            'References Count': 'references_count',
            'Citing Works Count': 'scholarly_citations_count',
            'Is Open Access': 'isopen_access',
            'Open Access License': None,
            'Open Access Colour': 'open_access'
        }

main_words = [
    'Urban',
    'City',
]

sub_words = [
    'Lockdown',
    'Covid',
    'Resilience',
    'Research',
    'Adaptation',
    'Policy',
    'Planning',
    'Building',
    'Wind',
    'Simulation',
    'Quality',
    'Land',
    'Emission',
    'Climate',
    'Risk',
    'Carbon',
    'Energy',
    'Temperature',
    'Model',
    'Data',
    'Air',
    'Space',
    'Spatial',
    'Surface',
    'Thermal',
    'Heat',
    'Comfort',
    'Effect',
]